### PR TITLE
[Sync] Updated Version of LLaMa

### PR DESCRIPTION
**Pull request by Tameem-10xE**
I followed all of steps which you have told

Kindly merge this, so I can send next PR with the new vector functions

### CODE REVIEW

**Comment by mmhus** [comment]
Where are our commits? Why aren't they rebased on top of the previous changes?

**Review by mmhus — CHANGES_REQUESTED** [review]
see comment above

**Comment by mmhus** [comment]
The commits are missing from our side: 
image

**Comment by mmhus** [comment]
@alitariq4589 additionally I see that these people are using lots of different CI, we can just add Cloud-V here as well.

**Comment by mmhus** [comment]
@AhmadTameem I think I understand now, did you fix an conflicts in this sync?

**Comment by mmhus** [comment]
@AhmadTameem I've synced the branch by fast-forwarding master, please remove the space change in your branch and repush, @alitariq4589 Please figure out how to add our CI to the llama pipeline. If needed we need to figure out how to get CI to work without token issues.

**Comment by Tameem-10xE** [comment]
@mmhus I have removed the space change

**Pull request closed without merging**
